cicero_script_path: /hpc/projects/data.science/yangjoon.kim/zebrahub_multiome/zebrahub-multiome-analysis/scripts/run_02_compute_CCANS_cicero.R
assay: "ATAC"
peaktype: "CRG_arc"
dim_reduced: "UMAP.ATAC"