# Define the target files, usually good practice
rule all:
    input:
        rds="{output_filepath}/{data_id}_processed.RDS",
        h5ad_rna="{output_filepath}/{data_id}_RNA.h5ad",
        h5ad_atac="{output_filepath}/{data_id}_ATAC.h5ad"

rule preprocess_multiome_data:
    input:
        #raw_data_path="{raw_data_path}",
        raw_data_path=config["raw_data_path"],
        gref=config["gref_path"],
        reference=config["reference"],
    output:
        rds="{output_filepath}/{data_id}_processed.RDS",
        h5ad_rna="{output_filepath}/{data_id}_RNA.h5ad",
        h5ad_atac="{output_filepath}/{data_id}_ATAC.h5ad"
    params:
        #reference=config["reference"],
        annotation_class=config["annotation_class"], # similarly for annotation_class if it's from the config
        script_path=config["01_script_path"]
    shell:
        """
        Rscript {params.script_path} {input.raw_data_path} {input.gref} {input.reference} {params.annotation_class} {output.rds} {wildcards.data_id}
        """